"""initial_schema_16_tables

Revision ID: 45da24af4d77
Revises: 
Create Date: 2026-04-17 01:34:47.750348
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45da24af4d77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_logs_created_at', 'admin_logs', ['created_at'], unique=False)
    op.create_index('idx_admin_logs_operator', 'admin_logs', ['operator'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_announcements_enabled', 'announcements', ['enabled'], unique=False)
    op.create_table('site_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=50), nullable=False),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('tool_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tool_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('credit_cost', sa.Integer(), nullable=False),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('membership_expiry', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('first_bonus_claimed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.CheckConstraint("role IN ('super_admin','admin','ultra','pro','normal','guest')", name='ck_users_role'),
    sa.CheckConstraint('credits >= 0', name='ck_users_credits_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('credit_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_records_created_at', 'credit_records', ['created_at'], unique=False)
    op.create_index('idx_credit_records_type', 'credit_records', ['type'], unique=False)
    op.create_index('idx_credit_records_user_id', 'credit_records', ['user_id'], unique=False)
    op.create_table('credit_schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('monthly_amount', sa.Integer(), nullable=False),
    sa.Column('next_distribution', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('remaining_months', sa.Integer(), nullable=False),
    sa.Column('billing_cycle', sa.String(length=10), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.CheckConstraint('monthly_amount > 0', name='ck_credit_schedules_amount'),
    sa.CheckConstraint('remaining_months >= 0', name='ck_credit_schedules_remaining'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_schedules_next_distribution', 'credit_schedules', ['next_distribution'], unique=False)
    op.create_index('idx_credit_schedules_user_id', 'credit_schedules', ['user_id'], unique=False)
    op.create_table('custom_libraries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_custom_libraries_user_id', 'custom_libraries', ['user_id'], unique=False)
    op.create_table('factory_assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('download_url', sa.String(length=1000), nullable=True),
    sa.Column('tool_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_factory_assets_created_at', 'factory_assets', ['created_at'], unique=False)
    op.create_index('idx_factory_assets_user_id', 'factory_assets', ['user_id'], unique=False)
    op.create_table('factory_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_factory_history_created_at', 'factory_history', ['created_at'], unique=False)
    op.create_index('idx_factory_history_user_id', 'factory_history', ['user_id'], unique=False)
    op.create_table('json_prompt_conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index('idx_json_prompt_conv_updated_at', 'json_prompt_conversations', ['updated_at'], unique=False)
    op.create_index('idx_json_prompt_conv_user_id', 'json_prompt_conversations', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=20), nullable=True),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('has_first_bonus', sa.Boolean(), nullable=False),
    sa.Column('first_bonus_credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.CheckConstraint("status IN ('pending','completed','refunded','cancelled')", name='ck_orders_status'),
    sa.CheckConstraint("type IN ('upgrade','recharge')", name='ck_orders_type'),
    sa.CheckConstraint('amount >= 0', name='ck_orders_amount_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_table('tool_usage_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_usage_logs_created_at', 'tool_usage_logs', ['created_at'], unique=False)
    op.create_index('idx_tool_usage_logs_tool_name', 'tool_usage_logs', ['tool_name'], unique=False)
    op.create_index('idx_tool_usage_logs_user_id', 'tool_usage_logs', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('pref_key', sa.String(length=50), nullable=False),
    sa.Column('pref_value', sa.String(length=500), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pref_key', name='uq_user_preferences_user_key')
    )
    op.create_index('idx_user_preferences_user_key', 'user_preferences', ['user_id', 'pref_key'], unique=True)
    op.create_table('worker_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('command', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('log_file', sa.String(length=255), nullable=True),
    sa.Column('device_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_worker_history_created_at', 'worker_history', ['created_at'], unique=False)
    op.create_index('idx_worker_history_user_id', 'worker_history', ['user_id'], unique=False)
    op.create_table('custom_lib_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('library_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('storage_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['custom_libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_custom_lib_files_library_id', 'custom_lib_files', ['library_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_custom_lib_files_library_id', table_name='custom_lib_files')
    op.drop_table('custom_lib_files')
    op.drop_index('idx_worker_history_user_id', table_name='worker_history')
    op.drop_index('idx_worker_history_created_at', table_name='worker_history')
    op.drop_table('worker_history')
    op.drop_index('idx_user_preferences_user_key', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index('idx_tool_usage_logs_user_id', table_name='tool_usage_logs')
    op.drop_index('idx_tool_usage_logs_tool_name', table_name='tool_usage_logs')
    op.drop_index('idx_tool_usage_logs_created_at', table_name='tool_usage_logs')
    op.drop_table('tool_usage_logs')
    op.drop_index('idx_orders_user_id', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_json_prompt_conv_user_id', table_name='json_prompt_conversations')
    op.drop_index('idx_json_prompt_conv_updated_at', table_name='json_prompt_conversations')
    op.drop_table('json_prompt_conversations')
    op.drop_index('idx_factory_history_user_id', table_name='factory_history')
    op.drop_index('idx_factory_history_created_at', table_name='factory_history')
    op.drop_table('factory_history')
    op.drop_index('idx_factory_assets_user_id', table_name='factory_assets')
    op.drop_index('idx_factory_assets_created_at', table_name='factory_assets')
    op.drop_table('factory_assets')
    op.drop_index('idx_custom_libraries_user_id', table_name='custom_libraries')
    op.drop_table('custom_libraries')
    op.drop_index('idx_credit_schedules_user_id', table_name='credit_schedules')
    op.drop_index('idx_credit_schedules_next_distribution', table_name='credit_schedules')
    op.drop_table('credit_schedules')
    op.drop_index('idx_credit_records_user_id', table_name='credit_records')
    op.drop_index('idx_credit_records_type', table_name='credit_records')
    op.drop_index('idx_credit_records_created_at', table_name='credit_records')
    op.drop_table('credit_records')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_table('tool_configs')
    op.drop_table('site_config')
    op.drop_index('idx_announcements_enabled', table_name='announcements')
    op.drop_table('announcements')
    op.drop_index('idx_admin_logs_operator', table_name='admin_logs')
    op.drop_index('idx_admin_logs_created_at', table_name='admin_logs')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
